### ISSUE TITLE
Mixin annotation on a class that is in default package?

### ISSUE THREAD

**Issue by jordanamr** [ReflxctionDev/tuna-bytes#2]
Hello!
I'm using Tuna-Bytes to patch a very old java program. However, all of the classes are in the default package, so I'm unable to use reference them in the @Mixin annotation, is there a way to get around that?

Thanks in advance.

**Comment by jordanamr** [comment]
So I realised it's possible to do something like `@Mixin(name = "myClass.class")` but it seems like it won't load: 
java.lang.NullPointerException: Class not found: myClass.class

The class is obviously in the classpath. I've tried loading the jar either in the -Djava.class.path argument BEFORE my tuna bytes wrapper, and also tried loading it in my wrapper main, before invoking `MixinsBootstrap.init();`

What am I missing ?

**Comment by jordanamr** [comment]
Interestingly, when I do that : 
![image](https://user-images.githubusercontent.com/55905781/210033250-9eb6f56f-164a-4d10-aa3b-a7015306a3cc.png)

I get this:
```
ok
java.lang.NullPointerException: Class not found: nj.class
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.arenareturns.shaded.tunabytes.bytecode.MixinEntry.targetReader(MixinEntry.java:38)
	at com.arenareturns.shaded.tunabytes.bytecode.MixinsBootstrap.init(MixinsBootstrap.java:58)
	at com.arenareturns.shaded.tunabytes.bytecode.MixinsBootstrap.init(MixinsBootstrap.java:34)
	at com.arenareturns.client.ArenaReturnsWrapper.main(ArenaReturnsWrapper.java:20)
```

So it seems like tunabyte is unable to load the class but I'm able to ?

**Comment by jordanamr** [comment]
I can confirm that using the library on classes in the default package was the issue, I relocated all classes beforehand using tiny remapper and everything works fine

**Comment by Revxrsal** [comment]
Hmm that's odd. What Java version are you using? In Java 9+, Tuna-Bytes looks for other classes in the same package to be able to find a suitable Module to load mixins into. I'm not sure how that would work on classes in the default package.

Also, I think the "Class not found: nj.class" is incorrect in this case. It is just a fallback message, and the issue is probably not relevant to whether the class is present or not.

Glad you managed to fix it by relocating, though.

**Comment by jordanamr** [comment]
> Hmm that's odd. What Java version are you using? In Java 9+, Tuna-Bytes looks for other classes in the same package to be able to find a suitable Module to load mixins into. I'm not sure how that would work on classes in the default package.
> 
> Also, I think the "Class not found: nj.class" is incorrect in this case. It is just a fallback message, and the issue is probably not relevant to whether the class is present or not.
> 
> Glad you managed to fix it by relocating, though.

I am using Java 8 but the classes were compiled on Java 5.
What's interesting is that I wasn't even able to do reflection or load the classes manually while it was in the default package...
But yeah I ended up relocating everything and it works fine, but I still find that odd

Thank you!
